### ISSUE TITLE
cv2.error: OpenCV(4.6.0) :-1: error: (-5:Bad argument) in function 'resize'

### ISSUE THREAD

**Issue by erikaemma** [BakingBrains/Real-Time_Background_remover#2]
```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "C:\Users\nobody\Documents\Projects\PycharmProjects\BakingBrains\Real-Time_Background_remover\BackgroundRemover.py", line 29, in <module>
    imgStack = cvzone.stackImages([img, imgOut], 2,1)
  File "C:\Users\nobody\anaconda3\lib\site-packages\cvzone\Utils.py", line 34, in stackImages
    imgList[i] = cv2.resize(imgList[i], (0, 0), None, scale, scale)
cv2.error: OpenCV(4.6.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - src data type = 17 is not supported
>  - Expected Ptr<cv::UMat> for argument 'src'
```

**Comment by BakingBrains** [comment]
@erikaemma I think something wrong with your image input. For me it just works fine.
Just now tested with new environment.
<html>
<body>


Pillow | 9.4.0 | 9.4.0
-- | -- | --
absl-py | 1.4.0 | 1.4.0
attrs | 22.2.0 | 22.2.0
cvzone | 1.5.6 | 1.5.6
cycler | 0.11.0 | 0.11.0
flatbuffers | 23.3.3 | 23.3.3
fonttools | 4.38.0 | 4.39.2
kiwisolver | 1.4.4 | 1.4.4
matplotlib | 3.5.3 | 3.7.1
mediapipe | 0.9.0.1 | 0.9.1.0
numpy | 1.21.6 | 1.24.2
opencv-contrib-python | 4.7.0.72 | 4.7.0.72
opencv-python | 4.7.0.72 | 4.7.0.72
packaging | 23.0 | 23.0
pip | 23.0.1 | 23.0.1
protobuf | 3.20.3 | 4.22.1
pyparsing | 3.0.9 | 3.0.9
python-dateutil | 2.8.2 | 2.8.2
setuptools | 67.6.0 | 67.6.0
six | 1.16.0 | 1.16.0
typing-extensions | 4.5.0 | 4.5.0


</body>
</html>

These my env modules.
Just did: 
pip install cvzone
pip install mediapipe

**Comment by erikaemma** [comment]
> 

It doesn't work for me. I have made those requirements to requirements.txt to install it.

**Comment by BakingBrains** [comment]
what's the python version? (mine 3.8)

**Comment by erikaemma** [comment]
> @erikaemma I think something wrong with your image input. For me it just works fine. Just now tested with new environment.
> 
> Pillow	9.4.0	9.4.0
> absl-py	1.4.0	1.4.0
> attrs	22.2.0	22.2.0
> cvzone	1.5.6	1.5.6
> cycler	0.11.0	0.11.0
> flatbuffers	23.3.3	23.3.3
> fonttools	4.38.0	4.39.2
> kiwisolver	1.4.4	1.4.4
> matplotlib	3.5.3	3.7.1
> mediapipe	0.9.0.1	0.9.1.0
> numpy	1.21.6	1.24.2
> opencv-contrib-python	4.7.0.72	4.7.0.72
> opencv-python	4.7.0.72	4.7.0.72
> packaging	23.0	23.0
> pip	23.0.1	23.0.1
> protobuf	3.20.3	4.22.1
> pyparsing	3.0.9	3.0.9
> python-dateutil	2.8.2	2.8.2
> setuptools	67.6.0	67.6.0
> six	1.16.0	1.16.0
> typing-extensions	4.5.0	4.5.0
> These my env modules. Just did: pip install cvzone pip install mediapipe

Resolved. Just delete the '. md' file, or judge in the code and only use the 'cv. read()' image.
